### ISSUE TITLE
getting 'noFilteredURL' thrown

### ISSUE THREAD

**Issue by nimrodbens** [eastriverlee/LLM.swift#19]
i'm trying to initialize 'deepset/roberta-base-squad2' model, and i get this error.

    let systemPrompt = "I want you to analyze an answer to a question."
    let bot = try await LLM(from: HuggingFaceModel("deepset/roberta-base-squad2", template: Template(systemPrompt: systemPrompt)))

and the error is being thrown in the init. to my understanding there is no link in the html file to download the model directly.

are the only two methods to interact with a model is to have it as a file locally or to download it?

i saw that some model weigh a few GB so either way is not feasible for my app.

i'm new with LLM so sorry if i asked obvious questions.

**Comment by eastriverlee** [comment]
sorry for the late reply. the code that you wrote is not working because the repository you chose has no gguf file. it has to be supported by `LLM.swift`'s backend which is `llama.cpp`. "deepset/roberta-base-squad2" is not supported in `llama.cpp`. if you are looking for a small model, i recommend you using "bartowski/h2o-danube2-1.8b-chat-GGUF" or tinyllama.
