### ISSUE TITLE
Getting a lot of errors

### ISSUE THREAD

**Issue by Arnav-arw** [eastriverlee/LLM.swift#3]
<img width="1512" alt="image" src="https://github.com/eastriverlee/LLM.swift/assets/88189594/5dd93e39-467a-4c09-8b34-fb53671a2404">

**Comment by eastriverlee** [comment]
this is happening because your application's name is also `LLM`. when it should be something different from the library's name. it's a simple name collision problem.

plus, you have to bundle the gguf model to use it. which means that you have to drag the gguf file that you downloaded (from hugging face for example) onto the xcode navigation bar on the left.

i'll update the `readme.md` soon to include more details.
