### ISSUE TITLE
Pin version of llama dependency

### ISSUE THREAD

**Issue by pgorzelany** [eastriverlee/LLM.swift#5]
Hey, could you pin a version of llama.cpp to a specific commit. That way you can be sure that the version of the library you ship won't break if there is a breaking change on llama.cpp master branch.

What do you think?

**Comment by eastriverlee** [comment]
Actually, it was my intention so that everybody using this can benefit from [llama.cpp](https://github.com/ggerganov/llama.cpp/tree/master)'s fast iteration speed, and since that is a huge library I know they are reluctant to introduce breaking changes.

But, I think maybe you got a point there. As I am adopting some new features and meet some bugs sometimes I wonder if this is my bad or because some changed in their side.

Is there any suggestion you can give? 
I don't want to update every time if [llama.cpp](https://github.com/ggerganov/llama.cpp/tree/master) supports a new architecture. not even automatically because the update is so frequent, and they don't have the versioning system to distinguish what's major update.
If we don't find a good solution, maybe I will release two versions for every major update, pinned and unpinned.

**Comment by pgorzelany** [comment]
Thanks for the quick update! I would just pin the version to a specific commit, probably one that is up to date and working with the version of this library at the time of releasing it.

**Comment by eastriverlee** [comment]
I created and deployed GitHub action that always pins the `Package.swift` to the most current branch of [llama.cpp](https://github.com/ggerganov/llama.cpp) and push to the `pinned` branch on every push I make manually. Now users has an option to choose the `pinned` branch if they are worried about dependency breaking.

**Comment by pedrodotavila** [comment]
how you guys would do that using it with Xcode dependencies?
